#!/bin/sh
mount -t sysfs sysfs /sys
mount -t proc proc /proc
mount -t devtmpfs udev /dev
sysctl -w kernel.printk="2 4 1 7"

# Simple Login Section
::askconsole -c /bin/sh # Launch /bin/sh on primary console
::respawn:-/bin/getty 38400 console  # Continuously respawn getty on the console